---
name: admiral

secrets:
  admiral_yaml:
    file: ./secrets/admiral.yaml
  mongo_yaml:
    file: ./secrets/mongo.yaml

x-admiral-template: &admiral-template
  build:
    context: .
    dockerfile: Dockerfile-admiral
  image: admiral
  init: true
  environment:
    ADMIRAL_CONFIG_FILE: /run/secrets/admiral.yaml
    ADMIRAL_CONFIG_SECTION: dev-mode
    ADMIRAL_WORKER_NAME: dev
  secrets:
    - source: admiral_yaml
      target: admiral.yaml
    - source: mongo_yaml
      target: config.yaml
  volumes:
    - ./src/admiral:/usr/src/admiral/admiral
    - ./tests:/home/cisa/tests
    - ./examples:/home/cisa/examples

services:
  celery-shell:
    <<: *admiral-template
    command: --interactive  # drop into an ipython celery shell

  bash:
    <<: *admiral-template
    entrypoint: /bin/sh

  test:
    <<: *admiral-template
    entrypoint: pytest
