---
name: admiral

configs:
  admiral_config:
    file: ./configs/admiral.yaml
  mongo_config:
    file: ./configs/mongo.yaml

x-admiral-template: &admiral-template
  build:
    context: .
    dockerfile: Dockerfile-admiral
  configs:
    - source: admiral_config
    - source: mongo_config
      target: config.yaml
  image: admiral
  init: true
  environment:
    ADMIRAL_CONFIG_FILE: "/admiral_config"
    ADMIRAL_CONFIG_SECTION: dev-mode
    ADMIRAL_WORKER_NAME: dev
  volumes:
    - ./src/admiral:/usr/src/admiral/admiral
    - ./tests:/home/cisa/tests
    - ./examples:/home/cisa/examples

services:
  celery-shell:
    <<: *admiral-template
    command: --interactive  # drop into an ipython celery shell

  bash:
    <<: *admiral-template
    entrypoint: /bin/sh

  test:
    <<: *admiral-template
    entrypoint: pytest
